import AppKit
import Foundation

/// Theo dõi NSPasteboard và phát hiện nội dung mới được copy.
///
/// Chiến lược: polling `changeCount` bằng timer nhẹ (mặc định 0.4s). Đây là cách
/// tin cậy nhất trên macOS vì hệ thống KHÔNG có notification công khai cho
/// pasteboard. `changeCount` là một số nguyên tăng dần — so sánh cực rẻ, chỉ khi
/// đổi mới thực sự đọc nội dung, nên CPU gần như 0 khi rảnh.
@MainActor
final class ClipboardMonitor {
    /// Gọi khi có item mới hợp lệ. Chạy trên main thread.
    var onNewItem: ((ClipboardItem) -> Void)?

    private let pasteboard: NSPasteboard
    private var timer: Timer?
    private var lastChangeCount: Int
    private let pollInterval: TimeInterval

    /// Bundle id của app đang bị bỏ qua (không lưu clipboard từ các app này).
    var ignoredBundleIds: Set<String> = []
    /// Bỏ qua nội dung có vẻ là mật khẩu (do app nguồn đánh dấu concealed).
    var ignoreConcealed: Bool = true

    /// changeCount do chính app này set khi "paste back" — để không tự lưu lại.
    private var selfWriteChangeCount: Int = -1

    init(pasteboard: NSPasteboard = .general, pollInterval: TimeInterval = 0.4) {
        self.pasteboard = pasteboard
        self.pollInterval = pollInterval
        self.lastChangeCount = pasteboard.changeCount
    }

    func start() {
        guard timer == nil else { return }
        let timer = Timer(timeInterval: pollInterval, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        // .common để vẫn chạy khi user đang tương tác menu/tracking.
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Đánh dấu rằng thay đổi tiếp theo là do app tự ghi (paste back) → bỏ qua.
    func markSelfWrite() {
        selfWriteChangeCount = pasteboard.changeCount
    }

    private func poll() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current

        // Bỏ qua thay đổi do chính app gây ra.
        if current == selfWriteChangeCount { return }

        // Tôn trọng nội dung ẩn/tạm (mật khẩu, OTP...) nếu app nguồn đánh dấu.
        if ignoreConcealed, isConcealedOrTransient() { return }

        let app = NSWorkspace.shared.frontmostApplication
        if let bundleId = app?.bundleIdentifier, ignoredBundleIds.contains(bundleId) {
            return
        }

        guard let item = readCurrentItem(sourceApp: app) else { return }
        onNewItem?(item)
    }

    private func isConcealedOrTransient() -> Bool {
        let types = pasteboard.types ?? []
        let markers: Set<NSPasteboard.PasteboardType> = [
            NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
            NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
            NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
        ]
        if !markers.isDisjoint(with: Set(types)) { return true }

        // Heuristic: phát hiện mật khẩu/quá dài/quá ngắn nghi ngờ
        if let string = pasteboard.string(forType: .string) {
            return isLikelySensitive(string)
        }
        return false
    }

    /// Heuristic phát hiện nội dung nhạy cảm: mật khẩu, token, OTP, thẻ tín dụng.
    private func isLikelySensitive(_ string: String) -> Bool {
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return false }

        // OTP 6 chữ số (thường gặp trong xác thực 2 yếu tố)
        if trimmed.range(of: #"^\d{6}$"#, options: .regularExpression) != nil { return true }

        // Credit card: 16 chữ số, có thể có dấu cách/gạch
        let digits = trimmed.filter(\.isNumber)
        if digits.count == 16 || digits.count == 15 {
            return true
        }

        // API key/token dài >40 ký tự không có khoảng trắng
        if trimmed.count > 40, !trimmed.contains(" ") {
            // Loại trừ URL dài
            if !trimmed.hasPrefix("http") {
                return true
            }
        }

        // Dòng chứa "password", "passwd", "secret" + dấu hai chấm hoặc dấu bằng
        let lower = trimmed.lowercased()
        let sensitiveKeywords = ["password", "passwd", "secret", "api[_-]?key", "token", "auth"]
        for keyword in sensitiveKeywords where lower.range(of: keyword, options: .regularExpression) != nil {
            return true
        }

        return false
    }

    private func readCurrentItem(sourceApp: NSRunningApplication?) -> ClipboardItem? {
        // 1) Ảnh (dữ liệu ảnh trực tiếp)
        if let imageItem = readImageItem(sourceApp: sourceApp) {
            return imageItem
        }
        // 2) Rich text (RTF/RTFD)
        if let rt = RichTextUtils.readRTF(from: pasteboard) {
            return ClipboardItem(
                content: rt.plainText,
                type: .richText,
                sourceAppBundleId: sourceApp?.bundleIdentifier,
                sourceAppName: sourceApp?.localizedName,
                richTextData: rt.rtfData
            )
        }
        // 3) File (URL bookmark)
        if let fileItem = readFileItem(sourceApp: sourceApp) {
            return fileItem
        }
        // 4) Text / URL / Color
        guard let string = pasteboard.string(forType: .string) else { return nil }
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return nil }

        return ClipboardItem(
            content: string,
            type: Self.detectType(string),
            sourceAppBundleId: sourceApp?.bundleIdentifier,
            sourceAppName: sourceApp?.localizedName
        )
    }

    private func readImageItem(sourceApp: NSRunningApplication?) -> ClipboardItem? {
        guard let image = readImage() else { return nil }
        guard let png = ImageUtils.pngData(from: image) else { return nil }
        let (width, height) = ImageUtils.pixelSize(of: image)
        let thumb = ImageUtils.thumbnailData(from: image)
        return ClipboardItem(
            content: "Hình ảnh \(width)×\(height)",
            contentHash: ClipboardItem.hash(for: png),
            type: .image,
            sourceAppBundleId: sourceApp?.bundleIdentifier,
            sourceAppName: sourceApp?.localizedName,
            imageData: png,
            thumbnailData: thumb
        )
    }

    /// Đọc file từ pasteboard (chỉ non-image files — ảnh đã được xử lý ở readImageItem).
    private func readFileItem(sourceApp: NSRunningApplication?) -> ClipboardItem? {
        guard FileUtils.hasFiles(in: pasteboard) else { return nil }
        let files = FileUtils.readFileURLs(from: pasteboard)
        // Lọc bỏ file ảnh (đã xử lý ở readImageItem)
        let nonImageFiles = files.filter { !FileUtils.isImageUTI($0.uti) }
        guard let first = nonImageFiles.first else { return nil }

        let url = URL(fileURLWithPath: first.path)
        let bookmark = FileUtils.createBookmark(for: url)
        let size = FileUtils.formattedFileSize(at: first.path)
        let name = url.lastPathComponent

        return ClipboardItem(
            content: name + (size.isEmpty ? "" : " (\(size))"),
            type: .file,
            sourceAppBundleId: sourceApp?.bundleIdentifier,
            sourceAppName: sourceApp?.localizedName,
            fileBookmark: bookmark,
            filePath: first.path,
            fileUTI: first.uti
        )
    }

    /// Đọc ảnh từ pasteboard qua nhiều nguồn: dữ liệu ảnh trực tiếp (png/tiff),
    /// hoặc file ảnh được copy (public.file-url trỏ tới ảnh).
    private func readImage() -> NSImage? {
        // 1) Dữ liệu ảnh trực tiếp (screenshot, copy ảnh trong app/trình duyệt).
        let imageTypes: [NSPasteboard.PasteboardType] = [.png, .tiff]
        if let type = pasteboard.availableType(from: imageTypes),
           let data = pasteboard.data(forType: type),
           let image = NSImage(data: data) {
            return image
        }
        // 2) File ảnh được copy (vd từ Finder) → đọc từ URL nếu là định dạng ảnh.
        let imageExts: Set<String> = ["png", "jpg", "jpeg", "gif", "heic", "tiff", "bmp", "webp"]
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self]) as? [URL] {
            for url in urls where url.isFileURL {
                if imageExts.contains(url.pathExtension.lowercased()),
                   let image = NSImage(contentsOf: url) {
                    return image
                }
            }
        }
        // 3) Nguồn khác (PDF, một số app) — chỉ thử khi KHÔNG có text để tránh nhầm.
        if pasteboard.string(forType: .string) == nil,
           let image = NSImage(pasteboard: pasteboard), image.size.width > 0 {
            return image
        }
        return nil
    }

    /// Suy luận loại nội dung ở mức nhẹ (đủ dùng cho icon + lọc).
    static func detectType(_ string: String) -> ClipboardContentType {
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        if let url = URL(string: trimmed),
           let scheme = url.scheme?.lowercased(),
           ["http", "https", "ftp", "mailto", "file"].contains(scheme),
           !trimmed.contains(" ") {
            return .url
        }
        if isHexColor(trimmed) || isCSSColor(trimmed) {
            return .color
        }
        return .text
    }

    private static func isHexColor(_ text: String) -> Bool {
        guard text.hasPrefix("#") else { return false }
        let hex = text.dropFirst()
        guard hex.count == 6 || hex.count == 3 || hex.count == 8 else { return false }
        return hex.allSatisfy { $0.isHexDigit }
    }

    /// Phát hiện các định dạng màu CSS: rgb(r,g,b), rgba(r,g,b,a), tên màu cơ bản.
    private static func isCSSColor(_ text: String) -> Bool {
        let lower = text.lowercased()
        // rgb() / rgba()
        if lower.hasPrefix("rgb") {
            let noSpace = lower.filter { !$0.isWhitespace }
            let pattern = #"^rgba?\(\d{1,3}(,\d{1,3}){2}(,\d+(\.\d+)?)?\)$"#
            return noSpace.range(of: pattern, options: .regularExpression) != nil
        }
        // Tên màu cơ bản
        let colorNames: Set<String> = [
            "red", "green", "blue", "yellow", "orange", "purple", "pink",
            "brown", "black", "white", "gray", "cyan", "magenta"
        ]
        return colorNames.contains(lower)
    }
}
